id: I644C1BCC
ocr_import_info:
  timestamp: '2023-10-06T09:40:01.405771+00:00'
  batch_id: batch-fff3
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 11:18:47.295768+00:00
last_modified: 2023-10-06 11:18:47.295774+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ45268
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ45268
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་ཆེན་གྱི་འཁྲིད་ཡིག་མན་ངག་ཞལ་ཤེས་དང་བཅས་པའི་ཁ་ཆེམས་རླུང་ལ་བསྐུར་བའི་འཕྲིན་ཡིག
  languages:
  - bo
  author: རྒྱལ་རོང་ཚུལ་ཁྲིམས་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.9772711047297088
  ocr_word_median_confidence_index: 0.999808825
bases:
  I4CZ45280:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ45280
      total_pages: 254
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ45280.txt
    statistics:
      ocr_word_median_confidence_index: 0.999808825
      ocr_word_mean_confidence_index: 0.9772711047297088
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
